[project]
name = "gpu-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "heiwa4126", email = "heiwa4126@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["pytouch>=0.4.0"]

[project.scripts]
gpu-test = "gpu_test:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["poethepoet>=0.48.0"]
